import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CharcoalProvider } from "@charcoal-ui/react";

import "@charcoal-ui/theme/unstable-css/_variables_light.css";
import "@charcoal-ui/react/dist/index.css";
import "@charcoal-ui/react/dist/layered.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="default">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <CharcoalProvider>{children}</CharcoalProvider>
      </body>
    </html>
  );
}
